name = "offchain-resolver-for-dns-names"
main = "src/index.ts"
compatibility_date = "2023-03-15"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "offchain-resolver-for-dns-db"
database_id = "64e1a6a6-4bca-44d0-8760-24ed2fc5b874"

# The necessary secrets are:
# - PRIVATE_KEY
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
